name: trading_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  firebase_auth: ^5.6.2
  firebase_core: ^3.15.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_svg: ^2.2.0
  flutter_switch: ^0.3.2
  go_router: ^16.0.0
  google_fonts: ^6.2.1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svgs/
    - assets/fonts/

  fonts:
    - family: NunitoSans
      fonts:
        - asset: assets/fonts/Nunito_Sans/font1.ttf
          weight: 400
        - asset: assets/fonts/Nunito_Sans/font2.ttf
          weight: 700
          
        