// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEgKH04L7z5yrUxmEG8PmX88MPwStlC50',
    appId: '1:1089736444525:web:dc3984b3240428e6a90d64',
    messagingSenderId: '1089736444525',
    projectId: 'khamidov-trading',
    authDomain: 'khamidov-trading.firebaseapp.com',
    storageBucket: 'khamidov-trading.firebasestorage.app',
    measurementId: 'G-Q0JN80JT8F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB76tmjt1B6AwYG6n1UitBPkwUIQxD4OCU',
    appId: '1:1089736444525:android:6682bd26bba95808a90d64',
    messagingSenderId: '1089736444525',
    projectId: 'khamidov-trading',
    storageBucket: 'khamidov-trading.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDU0hdfGOhzJv-yeFqQDSam_e30sLm9G-o',
    appId: '1:1089736444525:ios:dcbf37f65c389f45a90d64',
    messagingSenderId: '1089736444525',
    projectId: 'khamidov-trading',
    storageBucket: 'khamidov-trading.firebasestorage.app',
    iosBundleId: 'com.example.tradingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDU0hdfGOhzJv-yeFqQDSam_e30sLm9G-o',
    appId: '1:1089736444525:ios:dcbf37f65c389f45a90d64',
    messagingSenderId: '1089736444525',
    projectId: 'khamidov-trading',
    storageBucket: 'khamidov-trading.firebasestorage.app',
    iosBundleId: 'com.example.tradingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEgKH04L7z5yrUxmEG8PmX88MPwStlC50',
    appId: '1:1089736444525:web:6f4e48a90aa85d6ea90d64',
    messagingSenderId: '1089736444525',
    projectId: 'khamidov-trading',
    authDomain: 'khamidov-trading.firebaseapp.com',
    storageBucket: 'khamidov-trading.firebasestorage.app',
    measurementId: 'G-WKP1P14BLT',
  );
}
